swagger: "2.0"
info:
  version: "0.0.1"
  title: gift-adviser-api API description
# during dev, should point to your local machine
#host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json

paths:
  /:
    get:
      tags:
      - homepage
      summary: Get homepage
      description: Get homepage
      operationId: homepage
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
  ErrorResponse:
    properties:
      error:
        type: string
  SuccessResponse:
    properties:
      success:
        type: boolean
